services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: personal_project
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: personal_project
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
